name: QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    name: Code QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: "auto"

      - name: Install Task
        uses: go-task/setup-task@01a4adf9db2d14c1de7a560f09170b6e0df736aa # v2.1.0

      - name: Prepare UV environment
        run: uv sync --all-groups --all-extras --frozen


      - name: QA task
        run: task qa
