name: QA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  qa:
    name: Code QA
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          enable-cache: "auto"

      - name: Install Task
        uses: go-task/setup-task@v2.1.0

      - name: Prepare UV environment
        run: uv sync --all-groups --all-extras --frozen


      - name: QA task
        run: task qa
